### ISSUE TITLE
Wasteland Odyssey Mod List 1.12

### ISSUE THREAD

**Issue by chiqors** [chiqors/WastelandOdyssey-MCJava#1]
## List of mods for upcoming new modpack for MC 1.12.2

Format to submit suggestion :
_[Type of mod (Priority)] - [Name Of Mod] - [Mod Page/Download Link]_

**Status** :
- Accepted = Mod will be included in the modpack
- Warning = Mod is having an issue
- Pending = Mod needs to do research
 
------------------------------

**Accepted**
- Ambience (Music Mod)
- CraftTweaker
- CraftPresence
- Enchiridion
- Enhanced Visual
- FTB Mods
- IgniteHUD
- Immersive Enginering
- JourneyMap
- Just Enough Items
- Lootable Bodies
- Lost Cities
- Lyncanites Mobs
- Modular Powersuits
- Tough As Nails
- UniDict
- VanillaFix

**Warning**
- Optifine

**Pending**
- Tinker's Construct
- Armory Expansion
- Construct Armory
- CoFHCore
- Cosmetic Armor
- Cyber Ware (Robotic Parts)
- Improved Backpacks
- InfiniTiC
- Vic's Modern Warfare
- Tinker's JEI plugin
- Valkirien Warfare
- Keywizard
- RedstoneFlux
- Mantle
- Code Chicken Lib
- Wanionlib
- ReBind
- BindTweaker
- Chisel
- Millenaria
- CustomNPC
- NuclearCraft
- Connected Texture
- IV toolkit
- Open Blocks
- Level Up Reloaded
- Goki Stats
- Animalium
- Mekanism
- Railcraft or Steve's carts reborn
- RebornCore
- OpenComputer
- Bibliocraft
- Mekanism generators
- Mekanism tools
- MekaTweaker
- Omlib
- Modular Turret
- Tinkers' Survival
- Tinkers' Complement
- Tinkers' Tool Leveling
- Vials
- Alternative Flux
- Immersive Tech
- Immersive Petrolleum
- Decocraft
- Bibliocraft
- Malisis Doors
- Malisis Core
- Chisel and Bits
- Davincci's vessels
- MovingWorld
- Techguns
- Sleeping Overhaul
- Cosmic Lib
- Tick Rate Changer
- Bigger Crafting Table
- Reskilable
- Recipe Research
- ModTweaker with it's core
- ContentTweaker with it's core
- Comforts
- Simple Fluid Tanks
- Simulated Nights
- Wired: More Augs
- How Fortunate

**Comment by XxFlameCatxX** [comment]
add me as an constributor

**Comment by XxFlameCatxX** [comment]
- Tinker's Construct
- Ambience+
- Armory Expansion
- Construct Armory
- CoFHCore
- Cosmetic Armor
- Craft Tweaker
- Cyber Ware (Robotic Parts)
- Immersive Enginering
- Improved Backpacks
- InfiniTiC
- Just Enought Items
- Lyncanites Mobs
- Modular Powersuits
- Vic's Modern Warfare
- Optifine
- Thermal Expansion, Thermal Dynamics, Thermal Foundation, Thermal Cultivation, Thermal Innovation
- Tinker's JEI plugin
- UniDict
- Valkirien Warfarea

**Comment by chiqors** [comment]
I have submitted mod list from XxFlameCatxX..

**Comment by XxFlameCatxX** [comment]
Keywizard, it will be very nescessary, cus the keybing are limited

**Comment by XxFlameCatxX** [comment]
mods in fault cus their core: 
- RedstoneFlux
- Mantle
- Code Chicken Lib
- Wanionlib

**Comment by XxFlameCatxX** [comment]
Rebind and BindTweaker, this or will substitute the Keywizard or still be keywizard

**Comment by XxFlameCatxX** [comment]
don't forgget "cofh world", it's a core too

**Comment by XxFlameCatxX** [comment]
issue: Optifine was crashing my game

**Comment by XxFlameCatxX** [comment]
chisel and bits and chisel 2, for more decoration

**Comment by XxFlameCatxX** [comment]
ender I/O mod

**Comment by XxFlameCatxX** [comment]
millenarie mod, config it to be more wasted land survivors

**Comment by XxFlameCatxX** [comment]
Recurrent complex, for custom buildings

**Comment by XxFlameCatxX** [comment]
nuclear craft

**Comment by XxFlameCatxX** [comment]
- connected texture mod
- ender core
- IV toolkit
these are some lost coremods

**Comment by XxFlameCatxX** [comment]
- Open Blocks

**Comment by XxFlameCatxX** [comment]
- goki stats
- animallium

**Comment by XxFlameCatxX** [comment]
remove dongles mike, it have magic content

**Comment by XxFlameCatxX** [comment]
- though as nails

**Comment by XxFlameCatxX** [comment]
- mekanism
- Railcraft or steve's carts reborn
- Tought as nails

**Comment by XxFlameCatxX** [comment]
- reborncore

**Comment by XxFlameCatxX** [comment]
- open computer
- bibliocraft
- mekanism generators
- mekanism tools
- MekaTweaker

**Comment by XxFlameCatxX** [comment]
- Nuclear Craft: Mekanism Liquid Integration - Craft Tweaker

**Comment by XxFlameCatxX** [comment]
- MekaTweaker

**Comment by XxFlameCatxX** [comment]
- omlib
- modular turrents

**Comment by XxFlameCatxX** [comment]
- Tinkers' Survival (disables vanila tools making early game more difficulty, also contains code to disable vanilla armours if Construct Armoury is installed and a bridge between TaN and Construct Armoury)
- Tinkers' Complement (adds some early game blocks that can provide earlier access to things that would normally require the smeltery)
- Tinkers' Tool Leveling (pretty simple, as you use tools they can gain new modifiers)
- Vials (adds various bottles for moving more specific amounts of fluid between modded machines and the Tinkers' Construct smeltery)
By: Ravena

**Comment by XxFlameCatxX** [comment]
- Alternative Flux
- Immersive Tech
- Immersive Petrolleum

**Comment by XxFlameCatxX** [comment]
- decocraft (put this one in warning, it's crashing my game)
- bibliocraft
- malisis doors
- malisis core
for furniture and stuffs
- don't forgget chisel and bits

**Comment by XxFlameCatxX** [comment]
- Davincci's vessels
- MovingWorld
Substitutes the valkirien warfare

**Comment by XxFlameCatxX** [comment]
- Techguns

**Comment by XxFlameCatxX** [comment]
- flans mod and content pack
for terrestrial vehicles

**Comment by XxFlameCatxX** [comment]
- Fex's Vehicle and Transportation Mod
- Fexcraft Common Library
for terrestrial vehicles

**Comment by XxFlameCatxX** [comment]
- Colytra

**Comment by XxFlameCatxX** [comment]
- minecraft transport simulator

**Comment by XxFlameCatxX** [comment]
- Sleeping Overhaul
- CosmicLib
- TickrateChanger
for realistic sleep

**Comment by XxFlameCatxX** [comment]
MFFS

**Comment by XxFlameCatxX** [comment]
- bigger crafting table
- OpenComputers Drivers for Tinkers Construct

**Comment by XxFlameCatxX** [comment]
- Reskilable
- Recipe research
- ModTweaker with it's core
- Content tweaker with it's core

**Comment by XxFlameCatxX** [comment]
- Comforts
- simple fluid tanks
- Simulated nights
