### ISSUE TITLE
modlists to add suggestion

### ISSUE THREAD

**Issue by XxFlameCatxX** [chiqors/WastelandOdyssey-MCJava#2]
- Tinker's Construct
- Ambience+
- Armory Expansion
- Construct Armory
- CoFHCore
- Cosmetic Armor
- Craft Tweaker
- Cyber Ware (Robotic Parts)
- Immersive Enginering
- Improved Backpacks
- InfiniTiC
- Just Enought Items
- Lyncanites Mobs
- Modular Powersuits
- Vic's Modern Warfare
- Optifine
- Thermal Expansion, Thermal Dynamics, Thermal Foundation, Thermal Cultivation, Thermal Innovation
- Tinker's JEI plugin
- UniDict
- Valkirien Warfare

**Comment by chiqors** [comment]
This is wrong post.. please go to https://github.com/HAN-105/wasteland-odyssey/issues/1 for submitting your mod list
